import type { Metadata } from "next";
import {Playfair_Display} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"
import Footer from "@/components/Footer"

const Font = Playfair_Display ({
  subsets : ["latin"],
  weight: ["400"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Font.className}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
